@startuml
Class Engine{
    -Shader _shader
    #EntityCollection Entities
    -bool _waitRestart
    #Engine(int xres, int yres)
    #void OnLoad()
    #void SetupResources()
    #void OnUnload()
    #void OnResize()
    #void OnRenderFrame(FrameEventArgs e)
    #void OnUpdateFrame(FrameEventArgs e)
    #void OnKeyDown(KeyboardKeyEventArgs e)
    #void OnKeyUp(KeyboardKeyEventArgs e)
    -void RestartGame()
    +void GameOver()
}

Interface ICollider{
    {abstract}+void OnCollide(Entity entity1, Entity entity2)
}

ICollider <|- AsteroidCollider
ICollider <|-- BulletCollider
ICollider <|-- ShipCollider
ICollider <|-- UfoCollider

Class AsteroidCollider{
    +void OnCollide(Entity entity1, Entity entity2)
}

Class BulletCollider{
    +void OnCollide(Entity entity1, Entity entity2)
}

Class ShipCollider{
    +void OnCollide(Entity entity1, Entity entity2)
}

Class UfoCollider{
    +void OnCollide(Entity entity1, Entity entity2)
}

@enduml